# fly.toml app configuration file generated for superapp-ke5bhg on 2026-02-14T11:07:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'superapp-ke5bhg'
primary_region = 'iad'

[build]

[mounts]
  source = "stock_data"
  destination = "/app/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
